### ISSUE TITLE
Compile errors in IntelliJ 2017.3

### ISSUE THREAD

**Issue by Zomis** [C06A/KUrlet#1]
I found this project from here: https://discuss.kotlinlang.org/t/compiling-kotlin-to-both-java-and-javascript-from-the-same-module/1944/4
As I am also interested in sharing code in Kotlin between JVM and JS, I cloned your repository, opened it in IntelliJ and noticed that there are compiler errors in `kurlet.jvm/com.helpchoice.kotlin.urlet.impl.ExpressionJvm` because of `import com.helpchoice.kotlin.urlet.Expression` being an unresolved reference.

Have you somehow gotten this to work in IntelliJ locally without any compiler errors?

**Comment by C06A** [comment]
Zomis,

Could you attach the build log?

I guess you didn't build the project, but just check the missing classes. Just build from the top once and needed classes will be copied in correct places for IntelliJ to find them for incremental build (to show syntactic errors).

This short coming of the project come from the workaround I try to find to share code between JVM and JS projects. With Kotlin/Multiplatform this should not be a problem. Once it will be officially released I am planning to redo this project into Multiplatform instead coping files around.

Thank you for interest in this project.

**Comment by C06A** [comment]
I guess the response was helpful to resolve the problem reported.

**Comment by Zomis** [comment]
Unfortunately I just haven't had time/motivation/priority to check on this again.

**Comment by C06A** [comment]
Sorry. 

I checked it again and updated dependencies. It is working for me for me now. 

Also I added info to artifact repo containing latest build of JVM JAR in case you just want to use it. 


Thank you for looking in this project
Hope you won’t have problem with it
Hope JetBrains will release Multiplatform support soon and I will be able to modify this project to take advantage of it. 

Tx
/CAB
